### ISSUE TITLE
When key is 'on', it turns into 'true'

### ISSUE THREAD

**Issue by vincent-thomas** [ptarjan/online-yaml-parser#12]
this
```
on:
```

becomes
```
{
	"true": null
}
```

**Comment by perlpunk** [comment]
That's correct. In YAML 1.1 (which pyyaml implements) `on` is another way to say `true`.
For a compact comparison of special values in YAML 1.1 and 1.2 see https://perlpunk.github.io/yaml-test-schema/schemas.html
