### ISSUE TITLE
Site appears to be down?

### ISSUE THREAD

**Issue by lol768** [ptarjan/online-yaml-parser#4]
http://yaml-online-parser.appspot.com/ returns a HTTP 404

**Comment by ptarjan** [comment]
crap, i bet app-engine turned me off. Thanks.

**Comment by lol768** [comment]
No problem, it's a neat little tool - I miss it when it's not available.

**Comment by ptarjan** [comment]
And we're back, sorry for that. I guess I should have read the "you must migrate in 3 years" emails more carefully.
